import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "SoftwareDesign-Solution Portfolio",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="de"
      className="h-full"
    >
      <body className="min-h-full">
        
        {children}
        
      </body>
    </html>
  );
}
