import type { Metadata } from "next";
import "./globals.css";
import Footer from "./_components/footer";
import Header from "./_components/header";
import { BackToTopButton } from "./_components/back-to-top-button";


export const metadata: Metadata = {
  title: "SoftwareDesign-Solution Portfolio",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="de"
      className="h-full"
    >
      <body className="min-h-full">
        
        <Header />

        <main>
          {children}
        </main>
        
        <Footer />

        <BackToTopButton />
        
      </body>
    </html>
  );
}
